trigger:
  branches:
    include:
      - master

pool:
  name: poolA
jobs:
- job: Print_Console_Job
  displayName: "Print Console Job"

  steps:
  - checkout: self
  - script: |
      mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=devsecops66_mavenproject \
        -Dsonar.organization=devsecops \  # Only if using SonarCloud
        -Dsonar.login=$(SONAR_TOKEN)
