
trigger:
- main

pool:
  poolA  # Use Ubuntu agent to support wget and tar commands

steps:
- script: |
    wget https://github.com/zaproxy/zaproxy/releases/latest/download/ZAP_2.14.0_Linux.tar.gz
    tar -xvf ZAP_2.14.0_Linux.tar.gz
    cd ZAP_2.14.0
    ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout $(Build.ArtifactStagingDirectory)/zap_report.html
  displayName: "Integrate DAST scan using OWASP ZAP in ADO DevSecOps Pipeline"

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/zap_report.html'
    artifactName: zap_report

- publish: $(Build.ArtifactStagingDirectory)/zap_report.html
  condition: always()
  artifact: zap_report.html
