trigger:
  branches:
    include:
      - master

pool:
  name: mypool
jobs:
- job: Sonar_SAST_Scan_Job
  container: maven:3.8.1-openjdk-17-slim
  steps:
  - checkout: self
  - script: |
      mvn verify package sonar:sonar \
      -Dsonar.host.url=https://sonarcloud.io/ \
      -Dsonar.organization=Pragyan \
      -Dsonar.projectKey=pragyanbeuria \
      -Dsonar.login=662a569b38c065fba0d07f11d56b7aca47e7c17d
