trigger:
  branches:
    include:
      - master

pool:
  name: mypool

jobs:
- job: Print_Console_Job
  displayName: "Print Console Job"

  steps:
  - checkout: self
  - script: |
      mvn verify package sonar:sonar \
      -Dsonar.host.url=https://sonarcloud.io/ \
      -Dsonar.organization=Pragyan \
      -Dsonar.projectKey=pragyanbeuria \
      -Dsonar.login=fa619f3ab0507feae30e285e75d5a197956e2566
      